
import { integer, pgTable, varchar, text, timestamp, boolean, jsonb, decimal, index, uniqueIndex, foreignKey, primaryKey, pgEnum } from 'drizzle-orm/pg-core';
import { v4 as uuidv4 } from 'uuid';
import { users } from './users';

// Competitors table (Simple)
export const competitors = pgTable('competitors', {
  id: text('id').primaryKey().$defaultFn(() => uuidv4()),
  user_id: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  name: varchar('name', { length: 255 }).notNull(),
  website: varchar('website', { length: 500 }),
  description: text('description'),
  strengths: jsonb('strengths').default('[]'),
  weaknesses: jsonb('weaknesses').default('[]'),
  opportunities: jsonb('opportunities').default('[]'),
  threats: jsonb('threats').default('[]'),
  market_position: varchar('market_position', { length: 100 }),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
});

// Competitor Profiles table (Detailed)
export const competitorProfiles = pgTable('competitor_profiles', {
  id: text('id').primaryKey().$defaultFn(() => uuidv4()),
  user_id: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  name: varchar('name', { length: 255 }).notNull(),
  domain: varchar('domain', { length: 255 }),
  description: text('description'),
  industry: varchar('industry', { length: 100 }),
  headquarters: varchar('headquarters', { length: 255 }),
  founded_year: integer('founded_year'),
  employee_count: integer('employee_count'),
  funding_amount: decimal('funding_amount', { precision: 15, scale: 2 }),
  funding_stage: varchar('funding_stage', { length: 50 }),
  threat_level: varchar('threat_level', { length: 20 }).notNull().default('medium'),
  monitoring_status: varchar('monitoring_status', { length: 20 }).notNull().default('active'),
  social_media_handles: jsonb('social_media_handles').default('{}'),
  key_personnel: jsonb('key_personnel').default('[]'),
  products: jsonb('products').default('[]'),
  market_position: jsonb('market_position').default('{}'),
  competitive_advantages: jsonb('competitive_advantages').default('[]'),
  vulnerabilities: jsonb('vulnerabilities').default('[]'),
  monitoring_config: jsonb('monitoring_config').default('{}'),
  last_analyzed: timestamp('last_analyzed'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
}, (table) => ({
  userIdIdx: index('competitor_profiles_user_id_idx').on(table.user_id),
  threatLevelIdx: index('competitor_profiles_threat_level_idx').on(table.threat_level),
  monitoringStatusIdx: index('competitor_profiles_monitoring_status_idx').on(table.monitoring_status),
  domainIdx: index('competitor_profiles_domain_idx').on(table.domain),
  industryIdx: index('competitor_profiles_industry_idx').on(table.industry),
}));

// Intelligence Data table
export const intelligenceData = pgTable('intelligence_data', {
  id: text('id').primaryKey().$defaultFn(() => uuidv4()),
  competitor_id: text('competitor_id').notNull().references(() => competitorProfiles.id, { onDelete: 'cascade' }),
  user_id: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  source_type: varchar('source_type', { length: 50 }).notNull(),
  source_url: varchar('source_url', { length: 1000 }),
  data_type: varchar('data_type', { length: 100 }).notNull(),
  raw_content: jsonb('raw_content'),
  extracted_data: jsonb('extracted_data').default('{}'),
  analysis_results: jsonb('analysis_results').default('[]'),
  confidence: decimal('confidence', { precision: 3, scale: 2 }).default('0.00'),
  importance: varchar('importance', { length: 20 }).notNull().default('medium'),
  tags: jsonb('tags').default('[]'),
  collected_at: timestamp('collected_at').defaultNow(),
  processed_at: timestamp('processed_at'),
  expires_at: timestamp('expires_at'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
}, (table) => ({
  competitorIdIdx: index('intelligence_data_competitor_id_idx').on(table.competitor_id),
  userIdIdx: index('intelligence_data_user_id_idx').on(table.user_id),
  sourceTypeIdx: index('intelligence_data_source_type_idx').on(table.source_type),
  dataTypeIdx: index('intelligence_data_data_type_idx').on(table.data_type),
  importanceIdx: index('intelligence_data_importance_idx').on(table.importance),
  collectedAtIdx: index('intelligence_data_collected_at_idx').on(table.collected_at),
  expiresAtIdx: index('intelligence_data_expires_at_idx').on(table.expires_at),
}));

// Competitor Alerts table
export const competitorAlerts = pgTable('competitor_alerts', {
  id: text('id').primaryKey().$defaultFn(() => uuidv4()),
  competitor_id: text('competitor_id').notNull().references(() => competitorProfiles.id, { onDelete: 'cascade' }),
  user_id: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  intelligence_id: text('intelligence_id').references(() => intelligenceData.id, { onDelete: 'set null' }),
  alert_type: varchar('alert_type', { length: 100 }).notNull(),
  severity: varchar('severity', { length: 20 }).notNull().default('info'),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description'),
  source_data: jsonb('source_data').default('{}'),
  action_items: jsonb('action_items').default('[]'),
  recommended_actions: jsonb('recommended_actions').default('[]'),
  is_read: boolean('is_read').default(false),
  is_archived: boolean('is_archived').default(false),
  acknowledged_at: timestamp('acknowledged_at'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
}, (table) => ({
  competitorIdIdx: index('competitor_alerts_competitor_id_idx').on(table.competitor_id),
  userIdIdx: index('competitor_alerts_user_id_idx').on(table.user_id),
  alertTypeIdx: index('competitor_alerts_alert_type_idx').on(table.alert_type),
  severityIdx: index('competitor_alerts_severity_idx').on(table.severity),
  isReadIdx: index('competitor_alerts_is_read_idx').on(table.is_read),
  isArchivedIdx: index('competitor_alerts_is_archived_idx').on(table.is_archived),
  createdAtIdx: index('competitor_alerts_created_at_idx').on(table.created_at),
}));

// Scraping Jobs table
export const scrapingJobs = pgTable('scraping_jobs', {
  id: text('id').primaryKey().$defaultFn(() => uuidv4()),
  competitor_id: text('competitor_id').notNull().references(() => competitorProfiles.id, { onDelete: 'cascade' }),
  user_id: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  job_type: varchar('job_type', { length: 50 }).notNull(),
  url: varchar('url', { length: 1000 }).notNull(),
  priority: varchar('priority', { length: 20 }).notNull().default('medium'),
  frequency_type: varchar('frequency_type', { length: 20 }).notNull().default('interval'),
  frequency_value: varchar('frequency_value', { length: 100 }).notNull(),
  frequency_timezone: varchar('frequency_timezone', { length: 50 }),
  next_run_at: timestamp('next_run_at').notNull(),
  last_run_at: timestamp('last_run_at'),
  retry_count: integer('retry_count').notNull().default(0),
  max_retries: integer('max_retries').notNull().default(3),
  status: varchar('status', { length: 20 }).notNull().default('pending'),
  config: jsonb('config').notNull().default('{}'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
}, (table) => ({
  competitorIdIdx: index('scraping_jobs_competitor_id_idx').on(table.competitor_id),
  userIdIdx: index('scraping_jobs_user_id_idx').on(table.user_id),
  statusIdx: index('scraping_jobs_status_idx').on(table.status),
  priorityIdx: index('scraping_jobs_priority_idx').on(table.priority),
  nextRunAtIdx: index('scraping_jobs_next_run_at_idx').on(table.next_run_at),
  jobTypeIdx: index('scraping_jobs_job_type_idx').on(table.job_type),
}));

// Scraping Job Results table
export const scrapingJobResults = pgTable('scraping_job_results', {
  id: text('id').primaryKey().$defaultFn(() => uuidv4()),
  job_id: text('job_id').notNull().references(() => scrapingJobs.id, { onDelete: 'cascade' }),
  success: boolean('success').notNull(),
  data: jsonb('data'),
  error: text('error'),
  execution_time: integer('execution_time').notNull(),
  changes_detected: boolean('changes_detected').notNull().default(false),
  retry_count: integer('retry_count').notNull().default(0),
  completed_at: timestamp('completed_at').defaultNow(),
  created_at: timestamp('created_at').defaultNow(),
}, (table) => ({
  jobIdIdx: index('scraping_job_results_job_id_idx').on(table.job_id),
  successIdx: index('scraping_job_results_success_idx').on(table.success),
  completedAtIdx: index('scraping_job_results_completed_at_idx').on(table.completed_at),
}));

// Competitive Opportunities table
export const competitiveOpportunities = pgTable('competitive_opportunities', {
  id: text('id').primaryKey().$defaultFn(() => uuidv4()),
  user_id: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  competitor_id: text('competitor_id').notNull().references(() => competitorProfiles.id, { onDelete: 'cascade' }),
  intelligence_id: text('intelligence_id').references(() => intelligenceData.id, { onDelete: 'set null' }),
  opportunity_type: varchar('opportunity_type', { length: 50 }).notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description').notNull(),
  confidence: decimal('confidence', { precision: 3, scale: 2 }).notNull(),
  impact: varchar('impact', { length: 20 }).notNull(),
  effort: varchar('effort', { length: 20 }).notNull(),
  timing: varchar('timing', { length: 20 }).notNull(),
  priority_score: decimal('priority_score', { precision: 5, scale: 2 }).notNull(),
  evidence: jsonb('evidence').default('[]'),
  recommendations: jsonb('recommendations').default('[]'),
  status: varchar('status', { length: 50 }).default('identified'),
  assigned_to: text('assigned_to').references(() => users.id, { onDelete: 'set null' }),
  implementation_notes: text('implementation_notes'),
  roi_estimate: decimal('roi_estimate', { precision: 10, scale: 2 }),
  actual_roi: decimal('actual_roi', { precision: 10, scale: 2 }),
  success_metrics: jsonb('success_metrics').default('{}'),
  tags: jsonb('tags').default('[]'),
  is_archived: boolean('is_archived').default(false),
  detected_at: timestamp('detected_at').defaultNow(),
  started_at: timestamp('started_at'),
  completed_at: timestamp('completed_at'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
}, (table) => ({
  userIdIdx: index('competitive_opportunities_user_id_idx').on(table.user_id),
  competitorIdIdx: index('competitive_opportunities_competitor_id_idx').on(table.competitor_id),
  opportunityTypeIdx: index('competitive_opportunities_type_idx').on(table.opportunity_type),
  impactIdx: index('competitive_opportunities_impact_idx').on(table.impact),
  statusIdx: index('competitive_opportunities_status_idx').on(table.status),
  priorityScoreIdx: index('competitive_opportunities_priority_score_idx').on(table.priority_score),
  detectedAtIdx: index('competitive_opportunities_detected_at_idx').on(table.detected_at),
  isArchivedIdx: index('competitive_opportunities_is_archived_idx').on(table.is_archived),
}));

// Opportunity Actions table
export const opportunityActions = pgTable('opportunity_actions', {
  id: text('id').primaryKey().$defaultFn(() => uuidv4()),
  opportunity_id: text('opportunity_id').notNull().references(() => competitiveOpportunities.id, { onDelete: 'cascade' }),
  user_id: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  action_type: varchar('action_type', { length: 50 }).notNull(),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description'),
  priority: varchar('priority', { length: 20 }).default('medium'),
  estimated_effort_hours: integer('estimated_effort_hours'),
  actual_effort_hours: integer('actual_effort_hours'),
  estimated_cost: decimal('estimated_cost', { precision: 10, scale: 2 }),
  actual_cost: decimal('actual_cost', { precision: 10, scale: 2 }),
  expected_outcome: text('expected_outcome'),
  actual_outcome: text('actual_outcome'),
  status: varchar('status', { length: 50 }).default('pending'),
  due_date: timestamp('due_date'),
  completed_at: timestamp('completed_at'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
}, (table) => ({
  opportunityIdIdx: index('opportunity_actions_opportunity_id_idx').on(table.opportunity_id),
  userIdIdx: index('opportunity_actions_user_id_idx').on(table.user_id),
  statusIdx: index('opportunity_actions_status_idx').on(table.status),
  priorityIdx: index('opportunity_actions_priority_idx').on(table.priority),
  dueDateIdx: index('opportunity_actions_due_date_idx').on(table.due_date),
}));

// Opportunity Metrics table
export const opportunityMetrics = pgTable('opportunity_metrics', {
  id: text('id').primaryKey().$defaultFn(() => uuidv4()),
  opportunity_id: text('opportunity_id').notNull().references(() => competitiveOpportunities.id, { onDelete: 'cascade' }),
  user_id: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  metric_name: varchar('metric_name', { length: 100 }).notNull(),
  metric_type: varchar('metric_type', { length: 50 }).notNull(),
  baseline_value: decimal('baseline_value', { precision: 15, scale: 4 }),
  target_value: decimal('target_value', { precision: 15, scale: 4 }),
  current_value: decimal('current_value', { precision: 15, scale: 4 }),
  unit: varchar('unit', { length: 50 }),
  measurement_date: timestamp('measurement_date').defaultNow(),
  notes: text('notes'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
}, (table) => ({
  opportunityIdIdx: index('opportunity_metrics_opportunity_id_idx').on(table.opportunity_id),
  userIdIdx: index('opportunity_metrics_user_id_idx').on(table.user_id),
  metricNameIdx: index('opportunity_metrics_metric_name_idx').on(table.metric_name),
  measurementDateIdx: index('opportunity_metrics_measurement_date_idx').on(table.measurement_date),
}));

// Competitor Activities table
export const competitorActivities = pgTable('competitor_activities', {
    id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
    competitor_id: text('competitor_id').notNull().references(() => competitorProfiles.id, { onDelete: 'cascade' }),
    user_id: text('user_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
    activity_type: varchar('activity_type', { length: 50 }).notNull(),
    title: varchar('title', { length: 255 }).notNull(),
    description: text('description'),
    source_url: varchar('source_url', { length: 1000 }),
    source_type: varchar('source_type', { length: 50 }).notNull(),
    importance: varchar('importance', { length: 20 }).notNull().default('medium'),
    confidence: decimal('confidence', { precision: 3, scale: 2 }).default('0.00'),
    metadata: jsonb('metadata').default('{}'),
    tags: jsonb('tags').default('[]'),
    detected_at: timestamp('detected_at').defaultNow(),
    created_at: timestamp('created_at').defaultNow(),
    updated_at: timestamp('updated_at').defaultNow(),
  }, (table) => ({
    competitorIdIdx: index('competitor_activities_competitor_id_idx').on(table.competitor_id),
    userIdIdx: index('competitor_activities_user_id_idx').on(table.user_id),
    activityTypeIdx: index('competitor_activities_activity_type_idx').on(table.activity_type),
    importanceIdx: index('competitor_activities_importance_idx').on(table.importance),
    detectedAtIdx: index('competitor_activities_detected_at_idx').on(table.detected_at),
  }));
