$kind: http-request
name: Get Task
method: GET
url: '{{baseUrl}}/api/tasks/{{taskId}}'
order: 3000
headers:
  - key: Content-Type
    value: application/json
pathVariables:
  - key: taskId
    value: ''
