name: SoloSuccess-Production-Deploy
run-name: Shipping SoloSuccess AI to the Cloud 🚀
on:
  push:
    branches:
      - main # This tells Gitea: "Only run this when I save code to the main branch"

jobs:
  deploy-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        # This step connects your local runner to the Vercel cloud project
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: "team_6ryfUri1WCv0dL5LAbYfnnrP"
          VERCEL_PROJECT_ID: "prj_dcQO7rZFCxxwHnxaorYGiyItkj8B"

      - name: Deploy to Production
        # We remove .git to prevent Vercel CLI from associating the deploy with the git commit author
        # who may not be a verified member of the Vercel Team on the project settings.
        run: |
          rm -rf .git
          vercel deploy --prod --force --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: "team_6ryfUri1WCv0dL5LAbYfnnrP"
          VERCEL_PROJECT_ID: "prj_dcQO7rZFCxxwHnxaorYGiyItkj8B"
