
import React, { useState, useEffect } from 'react';
import { Crosshair, Search, ShieldAlert, Target, Zap, AlertTriangle, Loader2, Eye, ArrowRight, Mail, X } from 'lucide-react';
import { geminiService } from '../services/geminiService';
import { CompetitorReport, AgentId } from '../types';
import { addXP, showToast } from '../services/gameService';
import { soundService } from '../services/soundService';
import { storageService } from '../services/storageService';
import { logError } from '../lib/logger';

interface CompetitorStalkerProps {
    onNavigate: (view: string) => void;
}

export const CompetitorStalker: React.FC<CompetitorStalkerProps> = ({}) => {
    const [input, setInput] = useState('');
    const [loading, setLoading] = useState(false);
    const [report, setReport] = useState<CompetitorReport (null);
    const [recentSearches, setRecentSearches] = useState<string[]>([]);
    const [showRecent, setShowRecent] = useState(false);
    const [error, setError] = useState<string (null);

    useEffect(() => {
        const saved = localStorage.getItem('solo_competitor_searches');
        if (saved) {
            setRecentSearches(JSON.parse(saved));
        }
    }, []);

    const handleScan = async () => {
        if (!input.trim()) return;

        setLoading(true);
        setError(null);
        setReport(null);
        soundService.playClick();

        // Use LEXI (Insight Engine) for analysis
        const result = await geminiService.generateCompetitorReport(input, AgentId.LEXI);

        if (result) {
            setReport(result);

            // Save to DB
            try {
                await storageService.saveCompetitorReport(result);
            } catch (e) {
                logError("Failed to save report", e);
            }

            // Save Search History
            const newSearches = [input, ...recentSearches.filter(s => s !== input)].slice(0, 5);
            setRecentSearches(newSearches);
            localStorage.setItem('solo_competitor_searches', JSON.stringify(newSearches));

            // Gamification
            const { leveledUp } = await addXP(50);
            showToast("INTEL ACQUIRED", "Competitor analysis complete.", "xp", 50);
            if (leveledUp) showToast("RANK UP!", "You have reached a new founder level.", "success");
            soundService.playSuccess();
        } else {
            setError("SCAN FAILED. TARGET UNREACHABLE OR SECURE.");
            soundService.playError();
        }

        setLoading(false);
    };

    const handleEmail = () => {
        if (!report) return;

        const subject = `INTEL DOSSIER: ${report.competitorName} [${report.threatLevel}]`;
        const body = `
MISSION BRIEF:
${report.missionBrief}

------------------------------------------------
THREAT LEVEL: ${report.threatLevel}
TARGET LINK: ${input}
------------------------------------------------

KEY VULNERABILITIES:
${report.vulnerabilities.map(v => `- ${v}`).join('\n')}

GENERATED BY SOLOSUCCESS AI
        `.trim();

        window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
        soundService.playClick();
    };

    return (
        <div className="min-h-[85vh] flex flex-col animate-in fade-in duration-500">
            {/* Header */}
            <div className="sticky top-0 safe-top z-10 mb-6 flex items-end justify-between border-b-2 border-gray-700 pb-6 bg-gradient-to-br from-neon-cyan/5 via-transparent to-neon-purple/5">
                <div>
                    <div className="flex items-center gap-2 text-neon-cyan font-mono text-xs font-bold uppercase tracking-widest mb-2">
                        <Eye size={14} /> Competitive Intelligence
                    </div>
                    <h2 className="font-orbitron text-4xl font-bold uppercase tracking-wider text-white drop-shadow-glow">COMPETITOR STALKER</h2>
                    <p className="text-gray-400 mt-2 font-mono">Deep-dive analysis and threat assessment.</p>
                </div>
            </div>

            <div className="max-w-3xl mx-auto w-full flex flex-col gap-8">

                {/* Search Bar */}
                <div className="relative z-20">
                    <div className={`bg-dark-card border-2 border-gray-700 p-2 rounded-sm flex gap-2 shadow-[0_0_20px_rgba(11,228,236,0.1)] transition-all relative overflow-hidden group ${loading ? 'opacity-50 pointer-events-none' : 'hover:border-neon-cyan/50'}`}>
                        <div className="absolute inset-0 bg-gradient-to-r from-neon-cyan/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" />
                        <div className="flex-1 relative z-10">
                            <div className="absolute inset-y-0 left-4 flex items-center pointer-events-none text-gray-500">
                                <Search size={14} className="md:w-5 md:h-5" />
                            </div>
                            <input
                                type="text"
                                placeholder="TARGET_URL OR COMPANY_NAME"
                                className="w-full bg-transparent border-none focus:ring-0 text-white placeholder-gray-600 pl-12 pr-4 py-4 font-mono text-lg tracking-wide uppercase disabled:opacity-50 disabled:cursor-not-allowed"
                                value={input}
                                disabled={loading}
                                onFocus={() => setShowRecent(true)}
                                onBlur={() => setTimeout(() => setShowRecent(false), 200)}
                                onChange={(e) => { setInput(e.target.value); if (error) setError(null); }}
                                onKeyDown={(e) => e.key === 'Enter' && handleScan()}
                                autoComplete="off"
                            />
                        </div>
                        <button
                            onClick={handleScan}
                            disabled={loading || !input.trim()}
                            className="border-2 border-neon-lime bg-neon-lime/10 text-neon-lime px-8 py-3 rounded-sm font-mono font-bold text-sm uppercase tracking-wider transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 shadow-[0_0_15px_rgba(57,255,20,0.2)] hover:bg-neon-lime/20 hover:shadow-[0_0_20px_rgba(57,255,20,0.4)] z-10"
                        >
                            {loading ? <Loader2 size={16} className="animate-spin" /> : <><Crosshair size={14} className="md:w-5 md:h-5" /> Analyze Competitor</>}
                        </button>
                    </div>

                    {/* Recent Searches Dropdown */}
                    {showRecent && recentSearches.length > 0 && !loading && (
                        <>
                            <div className="fixed inset-0 bg-black/70 backdrop-blur-md z-40 flex items-center justify-center md:hidden" onClick={() => setShowRecent(false)}>
                                <div className="bg-dark-card border-2 border-gray-700 rounded-sm p-4 w-11/12 max-w-md" onClick={e => e.stopPropagation()}>
                                    <div className="flex justify-between items-center mb-2">
                                        <h3 className="text-sm font-mono font-bold text-gray-200">Recent Targets</h3>
                                        <button onClick={() => setShowRecent(false)} className="text-gray-400 hover:text-white">
                                            <X size={16} />
                                        </button>
                                    </div>
                                    {recentSearches.map((s, i) => (
                                        <div
                                            key={i}
                                            onMouseDown={() => { setInput(s); handleScan(); }}
                                            className="px-4 py-3 hover:bg-neon-cyan/10 cursor-pointer text-sm text-gray-300 font-mono flex items-center gap-2 transition-colors"
                                        >
                                            <Target size={14} className="text-neon-cyan" /> {s}
                                        </div>
                                    ))}
                                </div>
                            </div>
                            <div className="hidden md:block absolute top-full left-0 right-0 mt-2 bg-dark-card border-2 border-gray-700 rounded-sm shadow-[0_0_20px_rgba(11,228,236,0.2)] overflow-hidden animate-in fade-in slide-in-from-top-2 duration-200 backdrop-blur-xl z-50">
                                <div className="px-4 py-2 text-[10px] font-mono font-bold text-gray-500 uppercase tracking-widest bg-dark-hover">Recent Targets</div>
                                {recentSearches.map((s, i) => (
                                    <div
                                        key={i}
                                        onMouseDown={() => { setInput(s); handleScan(); }}
                                        className="px-4 py-3 hover:bg-neon-cyan/10 cursor-pointer text-sm text-gray-300 font-mono flex items-center gap-2 transition-colors"
                                    >
                                        <Target size={14} className="text-neon-cyan" /> {s}
                                    </div>
                                ))}
                            </div>
                        </>
                    )}

                    {error && (
                        <div className="mt-4 p-4 bg-neon-magenta/10 border-2 border-neon-magenta/30 text-neon-magenta text-sm font-mono rounded-sm flex items-center gap-3 animate-in slide-in-from-top-2 backdrop-blur-sm">
                            <AlertTriangle size={16} /> {error}
                        </div>
                    )}
                </div>

                {/* Results Area */}
                {!loading && !report && !error && (
                    <div className="flex flex-col items-center justify-center py-20 text-center">
                        <div className="bg-dark-card border-2 border-gray-700 p-8 rounded-sm max-w-md backdrop-blur-sm">
                            <div className="w-16 h-16 bg-neon-cyan/10 rounded-full flex items-center justify-center mx-auto mb-6">
                                <Crosshair size={32} className="text-neon-cyan" />
                            </div>
                            <h3 className="font-orbitron text-xl font-bold uppercase tracking-wider text-white mb-2">Intelligence Gathering</h3>
                            <p className="text-gray-400 font-mono text-sm mb-8 leading-relaxed">
                                Enter a competitor&apos;s URL or name above to begin deep-dive analysis and threat assessment.
                            </p>
                            <button
                                onClick={() => document.querySelector('input')?.focus()}
                                className="w-full border-2 border-neon-lime bg-neon-lime/10 text-neon-lime hover:bg-neon-lime/20 font-mono font-bold py-3 rounded-sm transition-colors uppercase text-xs tracking-wider"
                            >
                                Track Your First Competitor
                            </button>
                        </div>
                    </div>
                )}

                {loading && (
                    <div className="flex flex-col items-center justify-center py-20 text-neon-cyan">
                        <div className="relative mb-8">
                            <div className="w-24 h-24 border-4 border-neon-cyan/30 rounded-full animate-ping"></div>
                            <div className="absolute inset-0 m-auto w-16 h-16 border-4 border-neon-cyan rounded-full animate-spin"></div>
                            <div className="absolute inset-0 m-auto w-2 h-2 bg-white rounded-full"></div>
                        </div>
                        <div className="font-mono text-xs uppercase tracking-widest space-y-2 text-center">
                            <p className="text-neon-cyan">Intercepting Data Packets...</p>
                            <p className="text-gray-500">Running Vulnerability Scan...</p>
                        </div>
                    </div>
                )}

                {report && !loading && (
                    <div className="space-y-8 animate-in slide-in-from-bottom-8 duration-700 pb-20">

                        {/* Mission Brief Header */}
                        <div className="bg-dark-card border-2 border-gray-700 rounded-sm p-8 relative overflow-hidden group">
                            <div className={`absolute top-0 left-0 w-1 h-full ${report.threatLevel === 'Critical' ? 'bg-neon-magenta shadow-[0_0_20px_rgba(255,0,110,0.5)]' :
                                report.threatLevel === 'High' ? 'bg-neon-orange shadow-[0_0_20px_rgba(255,102,0,0.5)]' :
                                    report.threatLevel === 'Medium' ? 'bg-neon-orange' : 'bg-neon-cyan'
                                }`}></div>

                            <div className="flex justify-between items-start mb-6 relative z-10">
                                <div>
                                    <div className="flex items-center gap-3 mb-2">
                                        <h3 className="font-orbitron text-3xl font-bold uppercase tracking-wider text-white drop-shadow-md">{report.competitorName}</h3>
                                        <span className={`px-3 py-1 rounded-sm text-xs font-mono font-bold uppercase tracking-wider border-2 ${report.threatLevel === 'Critical' ? 'bg-neon-magenta/10 text-neon-magenta border-neon-magenta/50' :
                                            report.threatLevel === 'High' ? 'bg-neon-orange/10 text-neon-orange border-neon-orange/50' :
                                                'bg-neon-cyan/10 text-neon-cyan border-neon-cyan/50'
                                            }`}>
                                            Threat: {report.threatLevel}
                                        </span>
                                    </div>
                                    <p className="text-gray-400 text-sm font-mono">Analyzed by Lexi // {new Date(report.generatedAt).toLocaleDateString()}</p>
                                </div>
                                <button
                                    onClick={handleEmail}
                                    className="flex items-center gap-2 px-4 py-2 bg-dark-hover hover:bg-neon-cyan/10 text-white rounded-sm text-xs font-mono font-bold uppercase tracking-wider transition-all border-2 border-gray-700 hover:border-neon-cyan/50"
                                >
                                    <Mail size={14} /> Dispatch Report
                                </button>
                            </div>

                            <div className="bg-dark-bg p-6 rounded-sm border-2 border-gray-700 backdrop-blur-sm relative z-10">
                                <p className="text-gray-200 text-lg leading-relaxed font-mono">&quot;{report.missionBrief}&quot;</p>
                            </div>
                        </div>

                        {/* Metrics Grid */}
                        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
                            {[
                                { label: 'Innovation', val: report.metrics.innovation },
                                { label: 'Market Presence', val: report.metrics.marketPresence },
                                { label: 'UX / Design', val: report.metrics.ux },
                                { label: 'Pricing Power', val: report.metrics.pricing },
                                { label: 'Velocity', val: report.metrics.velocity }
                            ].map((m, i) => (
                                <div key={i} className="bg-dark-card border-2 border-gray-700 p-4 rounded-sm flex flex-col items-center text-center hover:border-neon-cyan/50 transition-colors">
                                    <span className="text-[10px] font-mono font-bold text-gray-400 uppercase tracking-wider mb-2">{m.label}</span>
                                    <div className="relative w-16 h-16 flex items-center justify-center mb-1">
                                        <svg className="absolute inset-0 w-full h-full -rotate-90" viewBox="0 0 36 36">
                                            <path className="text-gray-700" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" strokeWidth="4" />
                                            <path className={`${m.val > 80 ? 'text-neon-magenta drop-shadow-[0_0_5px_rgba(255,0,110,0.5)]' : m.val > 50 ? 'text-neon-orange' : 'text-neon-cyan'}`}
                                                strokeDasharray={`${m.val}, 100`} d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" strokeWidth="4" />
                                        </svg>
                                        <span className="text-sm font-mono font-bold text-white">{m.val}</span>
                                    </div>
                                </div>
                            ))}
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

                            {/* Vulnerabilities */}
                            <div className="bg-dark-card border-2 border-gray-700 rounded-sm p-6 border-l-4 border-l-neon-magenta/50">
                                <h4 className="text-xs font-mono font-bold text-neon-magenta uppercase tracking-widest mb-6 flex items-center gap-2">
                                    <ShieldAlert size={16} /> Critical Vulnerabilities
                                </h4>
                                <ul className="space-y-4">
                                    {report.vulnerabilities.map((v, i) => (
                                        <li key={i} className="flex items-start gap-3 text-sm text-gray-300 font-mono group">
                                            <span className="text-neon-magenta mt-1 opacity-50 group-hover:opacity-100 transition-opacity">×</span>
                                            {v}
                                        </li>
                                    ))}
                                </ul>
                            </div>

                            {/* Strengths */}
                            <div className="bg-dark-card border-2 border-gray-700 rounded-sm p-6 border-l-4 border-l-neon-lime/50">
                                <h4 className="text-xs font-mono font-bold text-neon-lime uppercase tracking-widest mb-6 flex items-center gap-2">
                                    <Zap size={16} /> Defensive Strengths
                                </h4>
                                <ul className="space-y-4">
                                    {report.strengths.map((s, i) => (
                                        <li key={i} className="flex items-start gap-3 text-sm text-gray-300 font-mono group">
                                            <span className="text-neon-lime mt-1 opacity-50 group-hover:opacity-100 transition-opacity">✓</span>
                                            {s}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        </div>

                        {/* Intel Dump */}
                        <div className="bg-dark-card border-2 border-gray-700 rounded-sm p-6">
                            <h4 className="text-xs font-mono font-bold text-neon-cyan uppercase tracking-widest mb-6 flex items-center gap-2">
                                <Target size={16} /> Intercepted Intel
                            </h4>
                            <div className="space-y-3">
                                {report.intel.map((item, i) => (
                                    <div key={i} className="flex items-start gap-3 p-3 bg-dark-bg rounded-sm border-2 border-gray-700 hover:border-neon-cyan/30 transition-colors">
                                        <ArrowRight size={14} className="text-neon-cyan mt-1 shrink-0" />
                                        <p className="text-sm text-gray-300 font-mono">{item}</p>
                                    </div>
                                ))}
                            </div>
                        </div>

                    </div>
                )}
            </div>
        </div>
    );
};
